/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHelpRouteImport } from './routes/api/help'
import { Route as ApiClassifyRouteImport } from './routes/api/classify'
import { Route as ApiV1ComplianceEvaluateRouteImport } from './routes/api/v1/compliance/evaluate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelpRoute = ApiHelpRouteImport.update({
  id: '/api/help',
  path: '/api/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassifyRoute = ApiClassifyRouteImport.update({
  id: '/api/classify',
  path: '/api/classify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ComplianceEvaluateRoute = ApiV1ComplianceEvaluateRouteImport.update({
  id: '/api/v1/compliance/evaluate',
  path: '/api/v1/compliance/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/classify': typeof ApiClassifyRoute
  '/api/help': typeof ApiHelpRoute
  '/api/v1/compliance/evaluate': typeof ApiV1ComplianceEvaluateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/classify': typeof ApiClassifyRoute
  '/api/help': typeof ApiHelpRoute
  '/api/v1/compliance/evaluate': typeof ApiV1ComplianceEvaluateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/classify': typeof ApiClassifyRoute
  '/api/help': typeof ApiHelpRoute
  '/api/v1/compliance/evaluate': typeof ApiV1ComplianceEvaluateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/classify' | '/api/help' | '/api/v1/compliance/evaluate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/classify' | '/api/help' | '/api/v1/compliance/evaluate'
  id:
    | '__root__'
    | '/'
    | '/api/classify'
    | '/api/help'
    | '/api/v1/compliance/evaluate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiClassifyRoute: typeof ApiClassifyRoute
  ApiHelpRoute: typeof ApiHelpRoute
  ApiV1ComplianceEvaluateRoute: typeof ApiV1ComplianceEvaluateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/help': {
      id: '/api/help'
      path: '/api/help'
      fullPath: '/api/help'
      preLoaderRoute: typeof ApiHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classify': {
      id: '/api/classify'
      path: '/api/classify'
      fullPath: '/api/classify'
      preLoaderRoute: typeof ApiClassifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/compliance/evaluate': {
      id: '/api/v1/compliance/evaluate'
      path: '/api/v1/compliance/evaluate'
      fullPath: '/api/v1/compliance/evaluate'
      preLoaderRoute: typeof ApiV1ComplianceEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiClassifyRoute: ApiClassifyRoute,
  ApiHelpRoute: ApiHelpRoute,
  ApiV1ComplianceEvaluateRoute: ApiV1ComplianceEvaluateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
